package com.wizinno.apollo.app.domain;

import com.wizinno.apollo.app.domain.model.AppInstallInfo;
import java.util.Date;
import java.util.List;

import com.wizinno.apollo.app.dto.AppInstallAndDeviceDto;
import com.wizinno.apollo.common.condition.AppInstallsCondition;
import org.apache.ibatis.annotations.Param;

public interface AppInstallInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_install_info
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    int deleteByPrimaryKey(@Param("checkTime") Date checkTime, @Param("userId") String userId, @Param("devId") String devId, @Param("appPackage") String appPackage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_install_info
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    int insert(AppInstallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_install_info
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    AppInstallInfo selectByPrimaryKey(@Param("checkTime") Date checkTime, @Param("userId") String userId, @Param("devId") String devId, @Param("appPackage") String appPackage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_install_info
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    List<AppInstallInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_install_info
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    int updateByPrimaryKey(AppInstallInfo record);

    List<AppInstallAndDeviceDto> getAppInstalls(AppInstallsCondition con);

    Long getAppInstallsTotal(AppInstallsCondition con);

    Integer getAppInstallsByPK(@Param("checkTime") Date checkTime, @Param("userId") String userId,@Param("devId") String devId);
}