package com.wizinno.apollo.app.domain;

import com.wizinno.apollo.app.domain.model.Device;
import java.util.List;

import com.wizinno.apollo.common.condition.DeviceCondition;
import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    int deleteByPrimaryKey(@Param("devId") String devId, @Param("devImei") String devImei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    Device selectByPrimaryKey(@Param("devId") String devId, @Param("devImei") String devImei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    List<Device> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    int updateByPrimaryKey(Device record);

    Device getDeviceByDevImei(String devImei);

    List<Device> getDevices(DeviceCondition con);

    Long getDevicesTotal(DeviceCondition con);
}