package com.wizinno.apollo.app.domain;

import com.wizinno.apollo.app.domain.model.NetTestLog;
import com.wizinno.apollo.common.condition.NetTestCondition;
import org.apache.ibatis.annotations.Param;


import java.util.Date;
import java.util.List;

public interface NetTestLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_test_log
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    int deleteByPrimaryKey(String testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_test_log
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    int insert(NetTestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_test_log
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    NetTestLog selectByPrimaryKey(String testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_test_log
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    List<NetTestLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_test_log
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    int updateByPrimaryKey(NetTestLog record);

    List<NetTestLog> getNetTestLogs(NetTestCondition con);

    Long getNetTestLogsTotal(NetTestCondition con);

}