package com.wizinno.apollo.app.domain;

import com.wizinno.apollo.app.domain.model.NetworkSpeed;
import java.util.Date;
import java.util.List;

import com.wizinno.apollo.app.dto.UserAndNetworksDto;
import com.wizinno.apollo.common.condition.NetworksSpeedCondition;
import org.apache.ibatis.annotations.Param;

public interface NetworkSpeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_speed
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("timeStamp") Date timeStamp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_speed
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    int insert(NetworkSpeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_speed
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    NetworkSpeed selectByPrimaryKey(@Param("userId") String userId, @Param("timeStamp") Date timeStamp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_speed
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    List<NetworkSpeed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_speed
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    int updateByPrimaryKey(NetworkSpeed record);

    List<UserAndNetworksDto> getNetworksSpeeds(NetworksSpeedCondition con);

    Long getNetworksSpeedsTotal(NetworksSpeedCondition con);
}