package com.wizinno.apollo.app.domain;

import com.wizinno.apollo.app.domain.model.TmpTable;
import java.util.List;

public interface TmpTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_table
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    int deleteByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_table
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    int insert(TmpTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_table
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    TmpTable selectByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_table
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    List<TmpTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_table
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    int updateByPrimaryKey(TmpTable record);
}