package com.wizinno.apollo.app.domain;

import com.wizinno.apollo.app.domain.model.User;
import com.wizinno.apollo.common.condition.UserCondition;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    int updateByPrimaryKey(User record);

    User getUserByMobileNum(String mobileNum);

    User getUserByMobileNumOrUname(String uName);

    User getUserByUname(String uName);

    List<User> getUsers(UserCondition con);

    Long getUsersTotal(UserCondition con);

    List<User> getExceptionsUsers(UserCondition con);

    Long getExceptionsUsersTotal(UserCondition con);

    List<User> getDisabledUsers(UserCondition con);

    Long getDisabledUsersTotal(UserCondition con);

    List<User> getNopermissionUsers(UserCondition con);

    Long getNopermissionUsersTotal(UserCondition con);

    List<User> getExceptionsUsersAll();
}