package com.wizinno.apollo.app.domain.model;

import java.io.Serializable;
import java.util.Date;

public class AppInstallInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_install_info.check_time
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_install_info.user_id
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_install_info.dev_id
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private String devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_install_info.app_package
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private String appPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_install_info.app_name
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_install_info.app_ver
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private String appVer;

    private String uName;

    private String mobileNum;

    private String devImei;

    private Integer appInstallTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_install_info
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    public Integer getAppInstallTotal() {
        return appInstallTotal;
    }

    public void setAppInstallTotal(Integer appInstallTotal) {
        this.appInstallTotal = appInstallTotal;
    }

    public String getuName() {
        return uName;
    }

    public void setuName(String uName) {
        this.uName = uName;
    }

    public String getMobileNum() {
        return mobileNum;
    }

    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum;
    }

    public String getDevImei() {
        return devImei;
    }

    public void setDevImei(String devImei) {
        this.devImei = devImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_install_info.check_time
     *
     * @return the value of app_install_info.check_time
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_install_info.check_time
     *
     * @param checkTime the value for app_install_info.check_time
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_install_info.user_id
     *
     * @return the value of app_install_info.user_id
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_install_info.user_id
     *
     * @param userId the value for app_install_info.user_id
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_install_info.dev_id
     *
     * @return the value of app_install_info.dev_id
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public String getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_install_info.dev_id
     *
     * @param devId the value for app_install_info.dev_id
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public void setDevId(String devId) {
        this.devId = devId == null ? null : devId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_install_info.app_package
     *
     * @return the value of app_install_info.app_package
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public String getAppPackage() {
        return appPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_install_info.app_package
     *
     * @param appPackage the value for app_install_info.app_package
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public void setAppPackage(String appPackage) {
        this.appPackage = appPackage == null ? null : appPackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_install_info.app_name
     *
     * @return the value of app_install_info.app_name
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_install_info.app_name
     *
     * @param appName the value for app_install_info.app_name
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_install_info.app_ver
     *
     * @return the value of app_install_info.app_ver
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public String getAppVer() {
        return appVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_install_info.app_ver
     *
     * @param appVer the value for app_install_info.app_ver
     *
     * @mbggenerated Fri Sep 15 11:47:53 CST 2017
     */
    public void setAppVer(String appVer) {
        this.appVer = appVer == null ? null : appVer.trim();
    }
}