package com.wizinno.apollo.app.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Device implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.dev_id
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.dev_imei
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String devImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.dev_brand
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String devBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.dev_model
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String devModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.android_api_ver
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String androidApiVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.factory_os
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String factoryOs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.factory_os_ver
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String factoryOsVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.d_mobileNum
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private String dMobilenum;

    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.d_loginTime
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private Date dLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.state
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private Integer state;
    private String stateDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    private static final long serialVersionUID = 1L;

    public String getuName() {
        return uName;
    }

    public void setuName(String uName) {
        this.uName = uName;
    }

    public String getStateDesc() {
        return stateDesc;
    }

    public void setStateDesc(String stateDesc) {
        this.stateDesc = stateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.dev_id
     *
     * @return the value of device.dev_id
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.dev_id
     *
     * @param devId the value for device.dev_id
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setDevId(String devId) {
        this.devId = devId == null ? null : devId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.dev_imei
     *
     * @return the value of device.dev_imei
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getDevImei() {
        return devImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.dev_imei
     *
     * @param devImei the value for device.dev_imei
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setDevImei(String devImei) {
        this.devImei = devImei == null ? null : devImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.dev_brand
     *
     * @return the value of device.dev_brand
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getDevBrand() {
        return devBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.dev_brand
     *
     * @param devBrand the value for device.dev_brand
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setDevBrand(String devBrand) {
        this.devBrand = devBrand == null ? null : devBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.dev_model
     *
     * @return the value of device.dev_model
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getDevModel() {
        return devModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.dev_model
     *
     * @param devModel the value for device.dev_model
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setDevModel(String devModel) {
        this.devModel = devModel == null ? null : devModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.android_api_ver
     *
     * @return the value of device.android_api_ver
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getAndroidApiVer() {
        return androidApiVer;
    }

    public void setAndroidApiVer(String androidApiVer) {
        this.androidApiVer = androidApiVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.factory_os
     *
     * @return the value of device.factory_os
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getFactoryOs() {
        return factoryOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.factory_os
     *
     * @param factoryOs the value for device.factory_os
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setFactoryOs(String factoryOs) {
        this.factoryOs = factoryOs == null ? null : factoryOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.factory_os_ver
     *
     * @return the value of device.factory_os_ver
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getFactoryOsVer() {
        return factoryOsVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.factory_os_ver
     *
     * @param factoryOsVer the value for device.factory_os_ver
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setFactoryOsVer(String factoryOsVer) {
        this.factoryOsVer = factoryOsVer == null ? null : factoryOsVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.d_mobileNum
     *
     * @return the value of device.d_mobileNum
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public String getdMobilenum() {
        return dMobilenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.d_mobileNum
     *
     * @param dMobilenum the value for device.d_mobileNum
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setdMobilenum(String dMobilenum) {
        this.dMobilenum = dMobilenum == null ? null : dMobilenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.d_loginTime
     *
     * @return the value of device.d_loginTime
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public Date getdLogintime() {
        return dLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.d_loginTime
     *
     * @param dLogintime the value for device.d_loginTime
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setdLogintime(Date dLogintime) {
        this.dLogintime = dLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.state
     *
     * @return the value of device.state
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.state
     *
     * @param state the value for device.state
     *
     * @mbggenerated Sat Sep 02 17:01:25 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}