package com.wizinno.apollo.app.domain.model;

import java.io.Serializable;
import java.util.Date;

public class NetTestLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.test_id
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.test_time
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Date testTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.test_event
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Integer testEvent;

    private String testEventDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.user_name
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.mobile_num
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String mobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.device_imei
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String deviceImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.net_type
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String netType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.operator
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.ip_addr
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String ipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.ssid
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String ssid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.gps
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String gps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.mcc
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String mcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.mnc
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String mnc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.lac
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String lac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.cid
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.bsss
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String bsss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.neighbor_station_info
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String neighborStationInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.trans_speed_up
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Long transSpeedUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.trans_speed_down
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Long transSpeedDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.pakage_loss_prob
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String pakageLossProb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.ave_trans_delay
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Long aveTransDelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.trans_jitter_p
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Long transJitterP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.trans_jitter_n
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Long transJitterN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.err_type
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Integer errType;
    private String errTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.manual_click
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Integer manualClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.screen_shap
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private String screenShap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_test_log.dev_netspeed
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private Long devNetspeed;

    private String describe;

    private Integer isFrontApp;

    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table net_test_log
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    public Integer getIsFrontApp() {
        return isFrontApp;
    }

    public void setIsFrontApp(Integer isFrontApp) {
        this.isFrontApp = isFrontApp;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getErrTypeDesc() {
        return errTypeDesc;
    }

    public void setErrTypeDesc(String errTypeDesc) {
        this.errTypeDesc = errTypeDesc;
    }

    public String getTestEventDesc() {
        return testEventDesc;
    }

    public void setTestEventDesc(String testEventDesc) {
        this.testEventDesc = testEventDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.test_id
     *
     * @return the value of net_test_log.test_id
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.test_id
     *
     * @param testId the value for net_test_log.test_id
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTestId(String testId) {
        this.testId = testId == null ? null : testId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.test_time
     *
     * @return the value of net_test_log.test_time
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.test_time
     *
     * @param testTime the value for net_test_log.test_time
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.test_event
     *
     * @return the value of net_test_log.test_event
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Integer getTestEvent() {
        return testEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.test_event
     *
     * @param testEvent the value for net_test_log.test_event
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTestEvent(Integer testEvent) {
        this.testEvent = testEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.user_name
     *
     * @return the value of net_test_log.user_name
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.user_name
     *
     * @param userName the value for net_test_log.user_name
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.mobile_num
     *
     * @return the value of net_test_log.mobile_num
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.mobile_num
     *
     * @param mobileNum the value for net_test_log.mobile_num
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum == null ? null : mobileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.device_imei
     *
     * @return the value of net_test_log.device_imei
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getDeviceImei() {
        return deviceImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.device_imei
     *
     * @param deviceImei the value for net_test_log.device_imei
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setDeviceImei(String deviceImei) {
        this.deviceImei = deviceImei == null ? null : deviceImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.net_type
     *
     * @return the value of net_test_log.net_type
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getNetType() {
        return netType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.net_type
     *
     * @param netType the value for net_test_log.net_type
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setNetType(String netType) {
        this.netType = netType == null ? null : netType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.operator
     *
     * @return the value of net_test_log.operator
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.operator
     *
     * @param operator the value for net_test_log.operator
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.ip_addr
     *
     * @return the value of net_test_log.ip_addr
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.ip_addr
     *
     * @param ipAddr the value for net_test_log.ip_addr
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.ssid
     *
     * @return the value of net_test_log.ssid
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.ssid
     *
     * @param ssid the value for net_test_log.ssid
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setSsid(String ssid) {
        this.ssid = ssid == null ? null : ssid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.gps
     *
     * @return the value of net_test_log.gps
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.gps
     *
     * @param gps the value for net_test_log.gps
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.mcc
     *
     * @return the value of net_test_log.mcc
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getMcc() {
        return mcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.mcc
     *
     * @param mcc the value for net_test_log.mcc
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setMcc(String mcc) {
        this.mcc = mcc == null ? null : mcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.mnc
     *
     * @return the value of net_test_log.mnc
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getMnc() {
        return mnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.mnc
     *
     * @param mnc the value for net_test_log.mnc
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setMnc(String mnc) {
        this.mnc = mnc == null ? null : mnc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.lac
     *
     * @return the value of net_test_log.lac
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getLac() {
        return lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.lac
     *
     * @param lac the value for net_test_log.lac
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setLac(String lac) {
        this.lac = lac == null ? null : lac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.cid
     *
     * @return the value of net_test_log.cid
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.cid
     *
     * @param cid the value for net_test_log.cid
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.bsss
     *
     * @return the value of net_test_log.bsss
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getBsss() {
        return bsss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.bsss
     *
     * @param bsss the value for net_test_log.bsss
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setBsss(String bsss) {
        this.bsss = bsss == null ? null : bsss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.neighbor_station_info
     *
     * @return the value of net_test_log.neighbor_station_info
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getNeighborStationInfo() {
        return neighborStationInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.neighbor_station_info
     *
     * @param neighborStationInfo the value for net_test_log.neighbor_station_info
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setNeighborStationInfo(String neighborStationInfo) {
        this.neighborStationInfo = neighborStationInfo == null ? null : neighborStationInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.trans_speed_up
     *
     * @return the value of net_test_log.trans_speed_up
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Long getTransSpeedUp() {
        return transSpeedUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.trans_speed_up
     *
     * @param transSpeedUp the value for net_test_log.trans_speed_up
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTransSpeedUp(Long transSpeedUp) {
        this.transSpeedUp = transSpeedUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.trans_speed_down
     *
     * @return the value of net_test_log.trans_speed_down
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Long getTransSpeedDown() {
        return transSpeedDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.trans_speed_down
     *
     * @param transSpeedDown the value for net_test_log.trans_speed_down
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTransSpeedDown(Long transSpeedDown) {
        this.transSpeedDown = transSpeedDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.pakage_loss_prob
     *
     * @return the value of net_test_log.pakage_loss_prob
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getPakageLossProb() {
        return pakageLossProb;
    }

    public void setPakageLossProb(String pakageLossProb) {
        this.pakageLossProb = pakageLossProb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.ave_trans_delay
     *
     * @return the value of net_test_log.ave_trans_delay
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Long getAveTransDelay() {
        return aveTransDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.ave_trans_delay
     *
     * @param aveTransDelay the value for net_test_log.ave_trans_delay
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setAveTransDelay(Long aveTransDelay) {
        this.aveTransDelay = aveTransDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.trans_jitter_p
     *
     * @return the value of net_test_log.trans_jitter_p
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Long getTransJitterP() {
        return transJitterP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.trans_jitter_p
     *
     * @param transJitterP the value for net_test_log.trans_jitter_p
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTransJitterP(Long transJitterP) {
        this.transJitterP = transJitterP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.trans_jitter_n
     *
     * @return the value of net_test_log.trans_jitter_n
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Long getTransJitterN() {
        return transJitterN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.trans_jitter_n
     *
     * @param transJitterN the value for net_test_log.trans_jitter_n
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setTransJitterN(Long transJitterN) {
        this.transJitterN = transJitterN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.err_type
     *
     * @return the value of net_test_log.err_type
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Integer getErrType() {
        return errType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.err_type
     *
     * @param errType the value for net_test_log.err_type
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setErrType(Integer errType) {
        this.errType = errType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.manual_click
     *
     * @return the value of net_test_log.manual_click
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Integer getManualClick() {
        return manualClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.manual_click
     *
     * @param manualClick the value for net_test_log.manual_click
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setManualClick(Integer manualClick) {
        this.manualClick = manualClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.screen_shap
     *
     * @return the value of net_test_log.screen_shap
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public String getScreenShap() {
        return screenShap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.screen_shap
     *
     * @param screenShap the value for net_test_log.screen_shap
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setScreenShap(String screenShap) {
        this.screenShap = screenShap == null ? null : screenShap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_test_log.dev_netspeed
     *
     * @return the value of net_test_log.dev_netspeed
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public Long getDevNetspeed() {
        return devNetspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_test_log.dev_netspeed
     *
     * @param devNetspeed the value for net_test_log.dev_netspeed
     *
     * @mbggenerated Sat Sep 02 14:47:30 CST 2017
     */
    public void setDevNetspeed(Long devNetspeed) {
        this.devNetspeed = devNetspeed;
    }
}