package com.wizinno.apollo.app.domain.model;

import java.io.Serializable;
import java.util.Date;

public class NetworkSpeed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.user_id
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.time_stamp
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.upload_maximum
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Double uploadMaximum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.upload_minimum
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Double uploadMinimum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.upload_avg
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Double uploadAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.down_maximum
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Double downMaximum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.down_minimum
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Double downMinimum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.down_avg
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private Double downAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_speed.app_packages
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private String appPackages;

    private String netType;

    private String operator;


    private String ssid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table network_speed
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    private static final long serialVersionUID = 1L;


    public String getSsid() {
        return ssid;
    }

    public void setSsid(String ssid) {
        this.ssid = ssid;
    }

    public String getNetType() {
        return netType;
    }

    public void setNetType(String netType) {
        this.netType = netType;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Double getUploadMaximum() {
        return uploadMaximum;
    }

    public void setUploadMaximum(Double uploadMaximum) {
        this.uploadMaximum = uploadMaximum;
    }

    public Double getUploadMinimum() {
        return uploadMinimum;
    }

    public void setUploadMinimum(Double uploadMinimum) {
        this.uploadMinimum = uploadMinimum;
    }

    public Double getUploadAvg() {
        return uploadAvg;
    }

    public void setUploadAvg(Double uploadAvg) {
        this.uploadAvg = uploadAvg;
    }

    public Double getDownMaximum() {
        return downMaximum;
    }

    public void setDownMaximum(Double downMaximum) {
        this.downMaximum = downMaximum;
    }

    public Double getDownMinimum() {
        return downMinimum;
    }

    public void setDownMinimum(Double downMinimum) {
        this.downMinimum = downMinimum;
    }

    public Double getDownAvg() {
        return downAvg;
    }

    public void setDownAvg(Double downAvg) {
        this.downAvg = downAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_speed.user_id
     *
     * @return the value of network_speed.user_id
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_speed.user_id
     *
     * @param userId the value for network_speed.user_id
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_speed.time_stamp
     *
     * @return the value of network_speed.time_stamp
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_speed.time_stamp
     *
     * @param timeStamp the value for network_speed.time_stamp
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_speed.app_packages
     *
     * @return the value of network_speed.app_packages
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    public String getAppPackages() {
        return appPackages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_speed.app_packages
     *
     * @param appPackages the value for network_speed.app_packages
     *
     * @mbggenerated Tue Sep 26 15:43:55 CST 2017
     */
    public void setAppPackages(String appPackages) {
        this.appPackages = appPackages == null ? null : appPackages.trim();
    }
}