package com.wizinno.apollo.app.domain.model;

import java.io.Serializable;
import java.util.Date;

public class TmpTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_table.phone
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_table.code
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_table.type
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmp_table.time_stamp
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tmp_table
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_table.phone
     *
     * @return the value of tmp_table.phone
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_table.phone
     *
     * @param phone the value for tmp_table.phone
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_table.code
     *
     * @return the value of tmp_table.code
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_table.code
     *
     * @param code the value for tmp_table.code
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_table.type
     *
     * @return the value of tmp_table.type
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_table.type
     *
     * @param type the value for tmp_table.type
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmp_table.time_stamp
     *
     * @return the value of tmp_table.time_stamp
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmp_table.time_stamp
     *
     * @param timeStamp the value for tmp_table.time_stamp
     *
     * @mbggenerated Fri Oct 20 13:26:54 CST 2017
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }
}