package com.wizinno.apollo.app.domain.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_num
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String mobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.operator
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.net_system
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String netSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_sex
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private Integer uSex;

    private String uSexDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_address
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private String uAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_birthdate
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private Date uBirthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_reg_date
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private Date uRegDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private Integer state;
    private String stateDesc;

    private Integer age;

    private Date testTime;

    private String appName;

    private Integer isFrontApp;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    public Integer getIsFrontApp() {
        return isFrontApp;
    }

    public void setIsFrontApp(Integer isFrontApp) {
        this.isFrontApp = isFrontApp;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Date getTestTime() {
        return testTime;
    }

    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    public String getStateDesc() {
        return stateDesc;
    }

    public void setStateDesc(String stateDesc) {
        this.stateDesc = stateDesc;
    }

    public String getuSexDesc() {
        return uSexDesc;
    }

    public void setuSexDesc(String uSexDesc) {
        this.uSexDesc = uSexDesc;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_num
     *
     * @return the value of user.mobile_num
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_num
     *
     * @param mobileNum the value for user.mobile_num
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum == null ? null : mobileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.operator
     *
     * @return the value of user.operator
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.operator
     *
     * @param operator the value for user.operator
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.net_system
     *
     * @return the value of user.net_system
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getNetSystem() {
        return netSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.net_system
     *
     * @param netSystem the value for user.net_system
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setNetSystem(String netSystem) {
        this.netSystem = netSystem == null ? null : netSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_sex
     *
     * @return the value of user.u_sex
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public Integer getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_sex
     *
     * @param uSex the value for user.u_sex
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setuSex(Integer uSex) {
        this.uSex = uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_address
     *
     * @return the value of user.u_address
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public String getuAddress() {
        return uAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_address
     *
     * @param uAddress the value for user.u_address
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setuAddress(String uAddress) {
        this.uAddress = uAddress == null ? null : uAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_birthdate
     *
     * @return the value of user.u_birthdate
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public Date getuBirthdate() {
        return uBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_birthdate
     *
     * @param uBirthdate the value for user.u_birthdate
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setuBirthdate(Date uBirthdate) {
        this.uBirthdate = uBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_reg_date
     *
     * @return the value of user.u_reg_date
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public Date getuRegDate() {
        return uRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_reg_date
     *
     * @param uRegDate the value for user.u_reg_date
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setuRegDate(Date uRegDate) {
        this.uRegDate = uRegDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbggenerated Sat Sep 02 15:26:10 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}